# Generated by Django 4.2.18 on 2025-02-04 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "summary",
                    models.TextField(blank=True, max_length=500, verbose_name="摘要"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="articles/%Y/%m/", verbose_name="特色图片"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "发布")],
                        default="draft",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="articles.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-published_time"],
                "indexes": [
                    models.Index(
                        fields=["-published_time"],
                        name="articles_ar_publish_90db7d_idx",
                    )
                ],
            },
        ),
    ]
